services:
  db:
    image: postgres:16-alpine
    container_name: quiz_postgres_db
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - quiz-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: quiz_keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    networks:
      - quiz-net
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - db

  infisical-db:
    image: postgres:16-alpine
    container_name: infisical_postgres_db
    environment:
      POSTGRES_DB: infisical_db
      POSTGRES_USER: infisical
      POSTGRES_PASSWORD: infisical_password
    networks:
      - quiz-net
    volumes:
      - infisical_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infisical -d infisical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  infisical-redis:
    image: redis:7-alpine
    container_name: infisical_redis_cache
    networks:
      - quiz-net

  infisical:
    image: infisical/infisical:latest
    container_name: quiz_infisical_secrets
    environment:
      - PORT=8080
      - DB_CONNECTION_URI=postgres://infisical:infisical_password@infisical-db:5432/infisical_db
      - REDIS_URL=redis://infisical-redis:6379
      - ENCRYPTION_KEY=6c8d488e0b2302bbd03e95bc7ee8109d
      - AUTH_SECRET=35c6f62b0e2bfb7cdcd26e84d41fdf7d
      - SITE_URL=http://localhost:8000
    ports:
      - "8000:8080"
    networks:
      - quiz-net
    depends_on:
      infisical-db:
        condition: service_healthy
      infisical-redis:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_aspnet_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=quizdb;Username=postgres;Password=postgres
      - Keycloak__Authority=http://keycloak:8080/auth/realms/quizmaster-realm
      - Keycloak__AdminUrl=http://keycloak:8080/auth
      - Keycloak__Realm=quizmaster-realm
      - Keycloak__AdminUsername=admin
      - Keycloak__AdminPassword=admin
      - INFISICAL_API_URL=http://infisical:8080
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - TelegramBot__Token=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBAPP_URL=https://hasanovkamol.github.io/quiz-demo
    ports:
      - "5005:5000"
    networks:
      - quiz-net
    depends_on:
      db:
        condition: service_healthy
      infisical:
        condition: service_started

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: quiz_angular_ui
    ports:
      - "8081:80"
    networks:
      - quiz-net
    depends_on:
      - backend

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: quiz_nginx_gateway
    ports:
      - "80:80"
    networks:
      - quiz-net
    depends_on:
      - ui
      - backend
      - keycloak
      - infisical

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: quiz_cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - quiz-net
    depends_on:
      - gateway


networks:
  quiz-net:
    driver: bridge

volumes:
  pgdata:
  infisical_pgdata:
